//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Start9.Host.Views
{
    
    public interface IModule
    {
        IConfiguration Configuration
        {
            get;
        }
        IMessageContract MessageContract
        {
            get;
        }
        IReceiverContract ReceiverContract
        {
            get;
        }
        void Initialize(IHost host);
    }
}

