//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Start9.Host.Adapters
{
    
    public class IMessageContractContractToViewHostAdapter : Start9.Host.Views.IMessageContract
    {
        private Start9.Api.Contracts.IMessageContractContract _contract;
        private System.AddIn.Pipeline.ContractHandle _handle;
        static IMessageContractContractToViewHostAdapter()
        {
        }
        public IMessageContractContractToViewHostAdapter(Start9.Api.Contracts.IMessageContractContract contract)
        {
            _contract = contract;
            _handle = new System.AddIn.Pipeline.ContractHandle(contract);
        }
        public System.Collections.Generic.IList<Start9.Host.Views.IMessageEntry> Entries
        {
            get
            {
                return System.AddIn.Pipeline.CollectionAdapters.ToIList<Start9.Api.Contracts.IMessageEntryContract, Start9.Host.Views.IMessageEntry>(_contract.Entries, Start9.Host.Adapters.IMessageEntryHostAdapter.ContractToViewAdapter, Start9.Host.Adapters.IMessageEntryHostAdapter.ViewToContractAdapter);
            }
        }
        internal Start9.Api.Contracts.IMessageContractContract GetSourceContract()
        {
            return _contract;
        }
    }
}

