//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Start9.Host.Adapters
{
    
    public class IMessageHostAdapter
    {
        internal static Start9.Host.Views.IMessage ContractToViewAdapter(Start9.Api.Contracts.IMessageContract contract)
        {
            if ((contract == null))
            {
                return null;
            }
            if (((System.Runtime.Remoting.RemotingServices.IsObjectOutOfAppDomain(contract) != true) 
                        && contract.GetType().Equals(typeof(IMessageViewToContractHostAdapter))))
            {
                return ((IMessageViewToContractHostAdapter)(contract)).GetSourceView();
            }
            else
            {
                return new IMessageContractToViewHostAdapter(contract);
            }
        }
        internal static Start9.Api.Contracts.IMessageContract ViewToContractAdapter(Start9.Host.Views.IMessage view)
        {
            if ((view == null))
            {
                return null;
            }
            if (view.GetType().Equals(typeof(IMessageContractToViewHostAdapter)))
            {
                return ((IMessageContractToViewHostAdapter)(view)).GetSourceContract();
            }
            else
            {
                return new IMessageViewToContractHostAdapter(view);
            }
        }
    }
}

