//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Start9.Host.Adapters
{
    
    public class IMessageEntryHostAdapter
    {
        internal static Start9.Host.Views.IMessageEntry ContractToViewAdapter(Start9.Api.Contracts.IMessageEntryContract contract)
        {
            if ((contract == null))
            {
                return null;
            }
            if (((System.Runtime.Remoting.RemotingServices.IsObjectOutOfAppDomain(contract) != true) 
                        && contract.GetType().Equals(typeof(IMessageEntryViewToContractHostAdapter))))
            {
                return ((IMessageEntryViewToContractHostAdapter)(contract)).GetSourceView();
            }
            else
            {
                return new IMessageEntryContractToViewHostAdapter(contract);
            }
        }
        internal static Start9.Api.Contracts.IMessageEntryContract ViewToContractAdapter(Start9.Host.Views.IMessageEntry view)
        {
            if ((view == null))
            {
                return null;
            }
            if (view.GetType().Equals(typeof(IMessageEntryContractToViewHostAdapter)))
            {
                return ((IMessageEntryContractToViewHostAdapter)(view)).GetSourceContract();
            }
            else
            {
                return new IMessageEntryViewToContractHostAdapter(view);
            }
        }
    }
}

