//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Start9.Host.Adapters
{
    
    public class IMessageContractViewToContractHostAdapter : System.AddIn.Pipeline.ContractBase, Start9.Api.Contracts.IMessageContractContract
    {
        private Start9.Host.Views.IMessageContract _view;
        public IMessageContractViewToContractHostAdapter(Start9.Host.Views.IMessageContract view)
        {
            _view = view;
        }
        public System.AddIn.Contract.IListContract<Start9.Api.Contracts.IMessageEntryContract> Entries
        {
            get
            {
                return System.AddIn.Pipeline.CollectionAdapters.ToIListContract<Start9.Host.Views.IMessageEntry, Start9.Api.Contracts.IMessageEntryContract>(_view.Entries, Start9.Host.Adapters.IMessageEntryHostAdapter.ViewToContractAdapter, Start9.Host.Adapters.IMessageEntryHostAdapter.ContractToViewAdapter);
            }
        }
        internal Start9.Host.Views.IMessageContract GetSourceView()
        {
            return _view;
        }
    }
}

