//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Start9.Host.Adapters
{
    
    public class IModuleHostAdapter
    {
        internal static Start9.Host.Views.IModule ContractToViewAdapter(Start9.Api.Contracts.IModuleContract contract)
        {
            if ((contract == null))
            {
                return null;
            }
            if (((System.Runtime.Remoting.RemotingServices.IsObjectOutOfAppDomain(contract) != true) 
                        && contract.GetType().Equals(typeof(IModuleViewToContractHostAdapter))))
            {
                return ((IModuleViewToContractHostAdapter)(contract)).GetSourceView();
            }
            else
            {
                return new IModuleContractToViewHostAdapter(contract);
            }
        }
        internal static Start9.Api.Contracts.IModuleContract ViewToContractAdapter(Start9.Host.Views.IModule view)
        {
            if ((view == null))
            {
                return null;
            }
            if (view.GetType().Equals(typeof(IModuleContractToViewHostAdapter)))
            {
                return ((IModuleContractToViewHostAdapter)(view)).GetSourceContract();
            }
            else
            {
                return new IModuleViewToContractHostAdapter(view);
            }
        }
    }
}

