//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Start9.Host.Adapters
{
    
    public class IModuleAssemblyHostAdapter
    {
        internal static Start9.Host.Views.IModuleAssembly ContractToViewAdapter(Start9.Api.Contracts.IModuleAssemblyContract contract)
        {
            if ((contract == null))
            {
                return null;
            }
            if (((System.Runtime.Remoting.RemotingServices.IsObjectOutOfAppDomain(contract) != true) 
                        && contract.GetType().Equals(typeof(IModuleAssemblyViewToContractHostAdapter))))
            {
                return ((IModuleAssemblyViewToContractHostAdapter)(contract)).GetSourceView();
            }
            else
            {
                return new IModuleAssemblyContractToViewHostAdapter(contract);
            }
        }
        internal static Start9.Api.Contracts.IModuleAssemblyContract ViewToContractAdapter(Start9.Host.Views.IModuleAssembly view)
        {
            if ((view == null))
            {
                return null;
            }
            if (view.GetType().Equals(typeof(IModuleAssemblyContractToViewHostAdapter)))
            {
                return ((IModuleAssemblyContractToViewHostAdapter)(view)).GetSourceContract();
            }
            else
            {
                return new IModuleAssemblyViewToContractHostAdapter(view);
            }
        }
    }
}

