//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Start9.Host.Views
{
    
    public interface IModuleAssembly
    {
        string Name
        {
            get;
        }
        string Description
        {
            get;
        }
        string Publisher
        {
            get;
        }
        System.Version Version
        {
            get;
        }
        System.Collections.Generic.IList<IModuleInstance> Instances
        {
            get;
        }
        IConfiguration SavedConfiguration
        {
            get;
        }
        IConfiguration CurrentConfiguration
        {
            get;
        }
        IMessageContract MessageContract
        {
            get;
        }
        IReceiverContract ReceiverContract
        {
            get;
        }
        void Kill(IModuleInstance instance);
        void KillAll();
        void Activate(bool initialize);
    }
}

