//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Start9.Host.Adapters
{
    
    public class IConfigurationEntryContractToViewHostAdapter : Start9.Host.Views.IConfigurationEntry
    {
        private Start9.Api.Contracts.IConfigurationEntryContract _contract;
        private System.AddIn.Pipeline.ContractHandle _handle;
        static IConfigurationEntryContractToViewHostAdapter()
        {
        }
        public IConfigurationEntryContractToViewHostAdapter(Start9.Api.Contracts.IConfigurationEntryContract contract)
        {
            _contract = contract;
            _handle = new System.AddIn.Pipeline.ContractHandle(contract);
        }
        public object Object
        {
            get
            {
                return _contract.Object;
            }
        }
        public string FriendlyName
        {
            get
            {
                return _contract.FriendlyName;
            }
        }
        internal Start9.Api.Contracts.IConfigurationEntryContract GetSourceContract()
        {
            return _contract;
        }
    }
}

