//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Start9.Host.Adapters
{
    
    public class IConfigurationViewToContractHostAdapter : System.AddIn.Pipeline.ContractBase, Start9.Api.Contracts.IConfigurationContract
    {
        private Start9.Host.Views.IConfiguration _view;
        public IConfigurationViewToContractHostAdapter(Start9.Host.Views.IConfiguration view)
        {
            _view = view;
        }
        public System.AddIn.Contract.IListContract<Start9.Api.Contracts.IConfigurationEntryContract> Entries
        {
            get
            {
                return System.AddIn.Pipeline.CollectionAdapters.ToIListContract<Start9.Host.Views.IConfigurationEntry, Start9.Api.Contracts.IConfigurationEntryContract>(_view.Entries, Start9.Host.Adapters.IConfigurationEntryHostAdapter.ViewToContractAdapter, Start9.Host.Adapters.IConfigurationEntryHostAdapter.ContractToViewAdapter);
            }
        }
        internal Start9.Host.Views.IConfiguration GetSourceView()
        {
            return _view;
        }
    }
}

