//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Start9.Host.Adapters
{
    
    public class IMessageContractToViewHostAdapter : Start9.Host.Views.IMessage
    {
        private Start9.Api.Contracts.IMessageContract _contract;
        private System.AddIn.Pipeline.ContractHandle _handle;
        static IMessageContractToViewHostAdapter()
        {
        }
        public IMessageContractToViewHostAdapter(Start9.Api.Contracts.IMessageContract contract)
        {
            _contract = contract;
            _handle = new System.AddIn.Pipeline.ContractHandle(contract);
        }
        public object Object
        {
            get
            {
                return _contract.Object;
            }
        }
        public Start9.Host.Views.IMessageEntry MessageEntry
        {
            get
            {
                return Start9.Host.Adapters.IMessageEntryHostAdapter.ContractToViewAdapter(_contract.MessageEntry);
            }
        }
        internal Start9.Api.Contracts.IMessageContract GetSourceContract()
        {
            return _contract;
        }
    }
}

