//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Start9.Host.Adapters
{
    
    public class IMessageEventHandlerContractToViewHostAdapter
    {
        private Start9.Api.Contracts.IMessageEventHandlerContract _contract;
        private System.AddIn.Pipeline.ContractHandle _handle;
        public IMessageEventHandlerContractToViewHostAdapter(Start9.Api.Contracts.IMessageEventHandlerContract contract)
        {
            _contract = contract;
            _handle = new System.AddIn.Pipeline.ContractHandle(contract);
        }
        public void Handler(object sender, Start9.Host.Views.MessageReceivedEventArgs args)
        {
            _contract.Handler(Start9.Host.Adapters.MessageReceivedEventArgsHostAdapter.ViewToContractAdapter(args));
        }
        internal Start9.Api.Contracts.IMessageEventHandlerContract GetSourceContract()
        {
            return _contract;
        }
    }
}

