//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Start9.Host.Adapters
{
    
    public class IMessageContractHostAdapter
    {
        internal static Start9.Host.Views.IMessageContract ContractToViewAdapter(Start9.Api.Contracts.IMessageContractContract contract)
        {
            if ((contract == null))
            {
                return null;
            }
            if (((System.Runtime.Remoting.RemotingServices.IsObjectOutOfAppDomain(contract) != true) 
                        && contract.GetType().Equals(typeof(IMessageContractViewToContractHostAdapter))))
            {
                return ((IMessageContractViewToContractHostAdapter)(contract)).GetSourceView();
            }
            else
            {
                return new IMessageContractContractToViewHostAdapter(contract);
            }
        }
        internal static Start9.Api.Contracts.IMessageContractContract ViewToContractAdapter(Start9.Host.Views.IMessageContract view)
        {
            if ((view == null))
            {
                return null;
            }
            if (view.GetType().Equals(typeof(IMessageContractContractToViewHostAdapter)))
            {
                return ((IMessageContractContractToViewHostAdapter)(view)).GetSourceContract();
            }
            else
            {
                return new IMessageContractViewToContractHostAdapter(view);
            }
        }
    }
}

