//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Start9.Host.Adapters
{
    
    public class IModuleViewToContractHostAdapter : System.AddIn.Pipeline.ContractBase, Start9.Api.Contracts.IModuleContract
    {
        private Start9.Host.Views.IModule _view;
        public IModuleViewToContractHostAdapter(Start9.Host.Views.IModule view)
        {
            _view = view;
        }
        public Start9.Api.Contracts.IConfigurationContract Configuration
        {
            get
            {
                return Start9.Host.Adapters.IConfigurationHostAdapter.ViewToContractAdapter(_view.Configuration);
            }
        }
        public Start9.Api.Contracts.IMessageContractContract MessageContract
        {
            get
            {
                return Start9.Host.Adapters.IMessageContractHostAdapter.ViewToContractAdapter(_view.MessageContract);
            }
        }
        public Start9.Api.Contracts.IReceiverContractContract ReceiverContract
        {
            get
            {
                return Start9.Host.Adapters.IReceiverContractHostAdapter.ViewToContractAdapter(_view.ReceiverContract);
            }
        }
        public virtual void Initialize(Start9.Api.Contracts.IHostContract host)
        {
            _view.Initialize(Start9.Host.Adapters.IHostHostAdapter.ContractToViewAdapter(host));
        }
        internal Start9.Host.Views.IModule GetSourceView()
        {
            return _view;
        }
    }
}

