//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Start9.Host.Adapters
{
    
    public class IReceiverEntryContractToViewHostAdapter : Start9.Host.Views.IReceiverEntry
    {
        private Start9.Api.Contracts.IReceiverEntryContract _contract;
        private System.AddIn.Pipeline.ContractHandle _handle;
        private Start9.Host.Adapters.IMessageEventHandlerViewToContractHostAdapter MessageReceived_Handler;
        private static System.Reflection.MethodInfo s_MessageReceivedEventAddFire;
		public event System.EventHandler<Start9.Host.Views.MessageReceivedEventArgs>MessageReceived{
			add{
				if (_MessageReceived == null)
				{
					_contract.MessageReceivedEventAdd(MessageReceived_Handler);
				}
				_MessageReceived += value;
				}
			remove{
					_MessageReceived -= value;
				if (_MessageReceived == null)
				{
					_contract.MessageReceivedEventRemove(MessageReceived_Handler);
				}
				}
		}
        static IReceiverEntryContractToViewHostAdapter()
        {
            s_MessageReceivedEventAddFire = typeof(IReceiverEntryContractToViewHostAdapter).GetMethod("Fire_MessageReceived", ((System.Reflection.BindingFlags)(36)));
        }
        public IReceiverEntryContractToViewHostAdapter(Start9.Api.Contracts.IReceiverEntryContract contract)
        {
            _contract = contract;
            _handle = new System.AddIn.Pipeline.ContractHandle(contract);
            MessageReceived_Handler = new Start9.Host.Adapters.IMessageEventHandlerViewToContractHostAdapter(this, s_MessageReceivedEventAddFire);
        }
        public string FriendlyName
        {
            get
            {
                return _contract.FriendlyName;
            }
        }
        private event System.EventHandler<Start9.Host.Views.MessageReceivedEventArgs> _MessageReceived;
        internal virtual void Fire_MessageReceived(Start9.Host.Views.MessageReceivedEventArgs args)
        {
            if ((_MessageReceived == null))
            {
            }
            else
            {
                _MessageReceived.Invoke(this, args);
            }
        }
        internal Start9.Api.Contracts.IReceiverEntryContract GetSourceContract()
        {
            return _contract;
        }
    }
}

