//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Start9.Host.Adapters
{
    
    public class IReceiverContractContractToViewHostAdapter : Start9.Host.Views.IReceiverContract
    {
        private Start9.Api.Contracts.IReceiverContractContract _contract;
        private System.AddIn.Pipeline.ContractHandle _handle;
        static IReceiverContractContractToViewHostAdapter()
        {
        }
        public IReceiverContractContractToViewHostAdapter(Start9.Api.Contracts.IReceiverContractContract contract)
        {
            _contract = contract;
            _handle = new System.AddIn.Pipeline.ContractHandle(contract);
        }
        public System.Collections.Generic.IList<Start9.Host.Views.IReceiverEntry> Entries
        {
            get
            {
                return System.AddIn.Pipeline.CollectionAdapters.ToIList<Start9.Api.Contracts.IReceiverEntryContract, Start9.Host.Views.IReceiverEntry>(_contract.Entries, Start9.Host.Adapters.IReceiverEntryHostAdapter.ContractToViewAdapter, Start9.Host.Adapters.IReceiverEntryHostAdapter.ViewToContractAdapter);
            }
        }
        internal Start9.Api.Contracts.IReceiverContractContract GetSourceContract()
        {
            return _contract;
        }
    }
}

