//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Start9.Host.Adapters
{
    
    public class MessageReceivedEventArgsViewToContractHostAdapter : System.AddIn.Pipeline.ContractBase, Start9.Api.Contracts.IMessageReceivedEventArgsContract
    {
        private Start9.Host.Views.MessageReceivedEventArgs _view;
        public MessageReceivedEventArgsViewToContractHostAdapter(Start9.Host.Views.MessageReceivedEventArgs view)
        {
            _view = view;
        }
        public Start9.Api.Contracts.IMessageContract Message
        {
            get
            {
                return Start9.Host.Adapters.IMessageHostAdapter.ViewToContractAdapter(_view.Message);
            }
        }
        internal Start9.Host.Views.MessageReceivedEventArgs GetSourceView()
        {
            return _view;
        }
    }
}

